### PR TITLE
Use official Hombrew link

### PR DESCRIPTION
**Pull request by vitorgalvao**
[It is maintained and up to date](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pup.rb). It’s more straightforward to users to install it this way.

### CODE REVIEW

**Comment by ericchiang** [comment]
Recipe needs a bit of updating: https://github.com/Homebrew/homebrew/issues/40270

Main reason I have a Homebrew recipe is for those who don't want to install from source. Might pup be better suited for the binary tap?

**Comment by vitorgalvao** [comment]
It could be included there, yes. We’d also accept it at [homebrew-cask](https://github.com/caskroom/homebrew-cask), if you want, but I don’t think it is needed.

I think most homebrew formulas don’t actually compile from source unless you specifically ask for it, these days. That’s what the `bottle` part should be taking care of.

**Comment by derimagia** [comment]
Yeah @vitorgalvao is correct here - when you install this from brew it by default grabs it from the bottle so it's already built. But if the user wants to they can build it - this is the advantage of the formula in homebrew that the one in the repo doesn't have

**Comment by vitorgalvao** [comment]
This is still relevant and the change should still be made.

However, I’m closing as there are now conflicts and I don’t have the fork anymore to fix them.

**Pull request closed without merging**
